Check build application

diff --git a/.github/workflows/api-tests.yml b/.github/workflows/api-tests.yml
--- a/.github/workflows/api-tests.yml
+++ b/.github/workflows/api-tests.yml
@@ -1,8 +1,87 @@
-name: ShareIt API Tests
+name: Explore With Me API Tests
 
 on:
   pull_request:
+  workflow_call:
 
 jobs:
-  build:
-    uses: yandex-praktikum/plus-smart-home-tech/.github/workflows/api-tests.yml@ci
+  check-repo:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check repo not fork and public
+        run: |
+          REPO=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${GITHUB_REPOSITORY}")
+          FORK=$(jq '.fork' <<< "$REPO")
+          PRIVATE=$(jq '.private' <<< "$REPO")
+          echo "FORK='$FORK', PRIVATE='$PRIVATE', GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER} "
+          if [[ "$FORK" == "true" ]]
+          then
+            echo "Use the repository automatically created by Yandex Practicum (works in fork repositories are not accepted)"
+            echo "Используйте только репозиторий созданный Yandex Practicum, работы в форк репозитории не принимаются"
+            exit -1
+          fi
+          if [[ "$GITHUB_REPOSITORY_OWNER" == "yandex-praktikum" ]]
+          then
+            echo "Use the repository automatically created by Yandex Practicum (works in fork repositories are not accepted)"
+            echo "Используйте только репозиторий созданный Yandex Practicum, работы в форк репозитории не принимаются"
+            exit -2
+          fi
+          if [[ "$PRIVATE" == "true" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
+          then
+            echo "Share your repository, make it public"
+            echo "Откройте доступ к вашему репозиторию, сделайте его публичным"
+            exit -3
+          fi
+        env:
+          GH_TOKEN: ${{ github.token }}
+
+      - name: Check files
+        run: |
+          PULL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/${GITHUB_REPOSITORY}/pulls/${PULL_NUMBER}/files?per_page=100 || true)
+          FILENAMES=$(jq '.[] | .filename' <<< "$PULL")
+          if [[ "$FILENAMES"  =~ "api-tests.yml" ]]
+          then
+            echo "The pull request contains the api-tests.yml file and cannot be modified. Remove it from PR"
+            echo "Pull request содержит файл api-tests.yml, его изменять нельзя. Удалите его из PR"
+            exit -1
+          fi
+          if [[ "$FILENAMES"  =~ "checkstyle.xml" ]]
+          then
+            echo "The pull request contains the checkstyle.xml file and cannot be modified. Remove it from PR"
+            echo "Pull request содержит файл checkstyle.xml, его изменять нельзя. Удалите его из PR"
+            exit -2
+          fi
+          if [[ "$FILENAMES"  =~ ".class" ]] || [[ "$FILENAMES"  =~ ".jar" ]] || [[ "$FILENAMES"  =~ "mvn" ]] || [[ "$FILENAMES"  =~ ".DS_Store" ]] \
+          || [[ "$FILENAMES"  =~ ".idea" ]] || [[ "$FILENAMES"  =~ ".iws" ]] || [[ "$FILENAMES"  =~ ".iml" ]] || [[ "$FILENAMES"  =~ ".ipr" ]] \
+          || [[ "$FILENAMES"  =~ ".db" ]] || [[ "$FILENAMES"  =~ ".log" ]] || [[ "$FILENAMES"  =~ "out/" ]] || [[ "$FILENAMES"  =~ "target/" ]]
+          then
+            echo "The pull request contains the binary files. Remove them (*.class, *.jar, *.DS_Store ...) from PR"
+            echo "Pull request содержит двоичные файлы. Удалите их (*.class, *.jar, *.DS_Store ...) из PR"
+            exit -3
+          fi
+          echo "PR files - OK"
+          exit
+        env:
+          PULL_NUMBER: ${{ github.event.number }}
+          GH_TOKEN: ${{ github.token }}
+
+  build-ewm:
+
+    needs: check-repo
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout target repo
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+          cache: maven
+
+      - name: Check and Build application
+        run: |
+          mvn verify --no-transfer-progress
